import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import ContextProvider from '@/context/ContextProvider';
import Header from '@/layout/Header';
import GlobalsLayout from '@/components/GlobalsLayout';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ContextProvider>
          <GlobalsLayout>
            <Header />
            {children}
          </GlobalsLayout>
        </ContextProvider>
      </body>
    </html>
  );
}
